---
- name: Get Leader/Follower
  shell: >
    set -o pipefail &&
      {{ zookeeper_health_check_command }} | grep Mode
  args:
    executable: /bin/bash
  register: leader_query
  changed_when: false
  check_mode: false
  ignore_errors: true

- debug:
    msg: "{{ leader_query.stdout }}"

- name: "Group Hosts by Zookeeper Mode: Follower or Leader"
  group_by:
    # Modes are either: follower, leader, standalone, will treat standalone as leaders
    key: "{{ follower_group if 'follower' in leader_query.stdout else leader_group }}"
  changed_when: false
  when: not leader_query.failed
